# Default values for analyze-plugin-sunsetting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: supergiant/analyze-plugin-sunsetting
  jobRepository: supergiant/analyze-registry-job
  tag: release-2.1-unstable
  jobTag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  externalHttpPort: 9922
  externalGrpcPort: 9999

rbac:
  create: true

resources:
   limits:
    cpu: 100m
    memory: 512Mi
   requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
