# Default values for analyze-plugin-sunsetting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: supergiant/analyze-plugin-sunsetting
  jobRepository: supergiant/analyze-registry-job
  tag: 0.0.1-18-g9de4680
  jobTag: 2.0.0-beta.2-6-gb035645
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  externalHttpPort: 9922
  externalGrpcPort: 9999


resources:
   limits:
    cpu: 100m
    memory: 512Mi
   requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
