apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - elasticsearch
          - -Des.insecure.allow.root=true
          - -Des.discovery.zen.ping.unicast.hosts=transport.{{ template "fullname" . }}-transport.svc.cluster.local:9300
          - -Des.path.data=/data-0,/data-1
          - -Des.path.logs=/data-0
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: data-0
          mountPath: /data-0
        - name: data-1
          mountPath: /data-1
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: data-0
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-data0
      - name: data-1
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-data1
      {{- else }}
      - name: data-0
        emptyDir: {}
      - name: data-1
        emptyDir: {}
      {{- end -}}
