apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-transport
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  - port: {{ .Values.transport.internalPort }}
    protocol: TCP
    name: {{ .Values.transport.name }}
  selector:
    app: {{ template "fullname" . }}
