# Default values for traefik.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
traefik:
  arch: amd64
  name: traefik-proxy
  service:
    externalServerPort: 443
    internalServerPort: 80
    externalUIPort: 80
    internalUIPort: 8080
    cert: CertHere
  image:
    repository: traefik
    tag: 1.4-alpine
    pullPolicy: IfNotPresent
resources: {}
