# Default values for analyze.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: supergiant/analyze
  nodeagentRepository: supergiant/analyze-nodeagent
  tag: latest
  nodeagentTag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  externalPort: 4443
  internalPort: 9091

ingress:
  enabled: false

resources:
  requests:
    cpu: 300m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true

etcd:
  endpoints:

  # Communication with etcd can be encrypted and authenticated with a certificate.
  # In order to enable it, add 'tls' section providing existing secret
  # containing CA certificate, client certificate and client key.
  # tls:
  #   existingSecret: etcd-tls-secret
  #   cert: client.crt
  #   key: client.key
  #   ca: ca.crt

cloudProviderType: "aws" ## need to be enum "aws", "do".

## TODO: it is nice to make these properties discoverable
aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: ""
