apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
    chart: {{ .Values.api.name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command:
          - /supergiant-api
          - --config-file
          - config.json
          {{- if .Values.api.support.enabled }}
          - --support-password
          - {{ .Values.api.support.password }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.api.service.internalPort }}
          volumeMounts:
          - name: sg-data
            mountPath: /tmp
  volumes:
  - name: sg-data
    hostPath:
      path: /efs/{{ .Values.uniqueurl }}
