apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
    chart: {{ .Values.api.name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: {{ .Values.api.arch }}
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          resources:
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command:
          - /supergiant-api
          {{- if .Values.api.psql }}
          - --psql-host
          - {{ .Values.api.psqlhost }}
          - --psql-db
          - {{ .Values.uniqueurl }}
          - --psql-user
          - {{ .Values.api.psqluser }}
          - --psql-pass
          - {{ .Values.api.psqlpass }}
          {{- end }}
          - --config-file
          - config.json
          {{- if .Values.api.support.enabled }}
          - --support-password
          - {{ .Values.api.support.password }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.api.service.internalPort }}
          volumeMounts:
          - name: sg-data
            mountPath: /tmp
      volumes:
      - name: sg-data
        hostPath:
          path: /efs/{{ .Values.uniqueurl }}
