apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
  name: {{ .Values.traefik.name }}-traefik-ui
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.traefik.name }}
    tier: proxy
  ports:
  - port: {{ .Values.traefik.service.externalServerPort }}
    targetPort: {{ .Values.traefik.service.internalServerPort }}
