apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.traefik.name }}-traefik-ui
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: {{ .Values.traefik.name }}-traefik-ui
    app: {{ .Values.traefik.name }}
    chart: {{ .Values.traefik.name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: proxy
  namespace: kube-system
spec:
  selector:
    app: {{ .Values.traefik.name }}
    tier: proxy
  ports:
  - port: {{ .Values.traefik.service.externalUIPort }}
    targetPort: {{ .Values.traefik.service.internalUIPort }}
