# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: elasticsearch
  tag: 2.4
  pullPolicy: IfNotPresent
service:
  name: http
  type: ClusterIP
  externalPort: 9200
  internalPort: 9200
transport:
  name: transport
  internalPort: 9300
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 8Gi
