{{- if and .Values.rbac.create .Values.serviceAccount.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "capacity.fullname" . }}-nodepod-permissions
  labels:
{{ include "capacity.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
{{- end }}