{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "capacity.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "capacity.labels" . | indent 4 }}
data:
  kubescaler.conf: |
    {{ .Values.config.kubescaler.raw }}
{{- end }}
