{{- if and .Values.rbac.create .Values.serviceAccount.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "capacity.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "capacity.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "capacity.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "capacity.fullname" . }}-configmap
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "capacity.fullname" . }}-configmap-default
  namespace: kube-system
  labels:
{{ include "capacity.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "capacity.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "capacity.fullname" . }}-configmap-default
  apiGroup: rbac.authorization.k8s.io
{{- end }}