{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "capacity.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "capacity.labels" . | indent 4 }}
{{- end }}