{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceaccount.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "analyze.name" . }}
    helm.sh/chart: {{ include "analyze.chart" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}